### ISSUE TITLE
Write boilerplate / pick architecture

### ISSUE THREAD

**Issue by batpad** [mapbox/osm-comments-frontend#1]
Figure out tools / libraries and boilerplate the front-end.

It seems like it would make sense to use ReactJS for this, even though my limited experience with it would mean I'd probably need a little bit of hand-holding / guidance.

@aaronlidman @tristen I was going to use basic boilerplate ideas from https://github.com/osmlab/to-fix - does this seem reasonable or are there other resources you think I should look at?

Would also love any links to reading that maybe useful for starting off doing stuff with React. Thanks!

/cc @rclark @geohacker

**Comment by tristen** [comment]
I need some context. What's this project about? Is it the frontend to a future `osm-comments-backend` project? From the README I see:

> Frontend application to query osm-comments-api

If this just a search interface? If that's the case I'm not sure you need React and would go more simpler here.

**Comment by batpad** [comment]
@tristen sorry, that did need more context:

This is the API repository that the front-end will talk to: https://github.com/mapbox/osm-comments-api

In short, it's just a way to track OSM Notes and comments on changesets, initially as more of an internal team for our data team to track their notes and comments, but ideally grow into something useful for the larger community.

I imagine there to be a simple search interface to input usernames that people are interested in, mark out a bounding box on the map to search within, and select date ranges. Results would be shown as a list. The app is read-only, I don't imagine any write operations being facilitated through it. It would, however, need permalinks for search queries.

I am quite comfortable implementing this either just gluing together some jquery or using Backbone, which I have some experience with, or using this opportunity to teach myself React if that does seem a good fit. Am super happy to go simple if you feel that's okay. Thanks for the inputs, @tristen .

**Comment by tristen** [comment]
Got it. Well you should use this opportunity to use React! I wouldn't look to [to-fix](https://github.com/osmlab/to-fix) as a boilerplate though. It's needlessly complex for what you need and I'd implement it differently these days :p 

I'd look at building this with just [React](http://npmjs.org/package/react) and [react-router](https://www.npmjs.com/package/react-router) and manage the state of the app in the component (i.e. no need for Flux etc.). The react-router project is chalk full of different examples for guidance. See https://github.com/rackt/react-router/tree/master/examples

**Comment by batpad** [comment]
Thank you, @tristen, this is exactly what I was looking for. Expect some pings in the coming days, if that's okay :)

**Comment by tristen** [comment]
:+1:
