### ISSUE TITLE
cannot query usernames with spaces

### ISSUE THREAD

**Issue by maning** [mapbox/osm-comments-frontend#24]
i.e. https://www.openstreetmap.org/user/Das%20Fantom

http://mapbox.github.io/osm-comments-frontend/#/changesets/?q=users:Das%20Fantom

**Comment by batpad** [comment]
So right now space is used as delimiter between parts of the query.

eg. if you query `users:manings,pratikyadav foobar` it will search for notes / changesets by manings or pratikyadav that have the word `foobar` in them.

This will require coming up with desired syntax for usernames with spaces, as well as adding that logic to the tokenizer. My guess is it would have to be something like `users:manings,"user with spaces",pratikyadav search terms`.
