### ISSUE TITLE
Text search for my username inconsistent

### ISSUE THREAD

**Issue by planemad** [mapbox/osm-comments-frontend#25]
Search for `PlaneMad` > 1 result. Search for `users:PlaneMad` > 3 results

Both should give 3 hits?

**Comment by batpad** [comment]
@planemad the feature to search with "users: ... " was not implemented. It now is. Searching for just `PlaneMad` would search the text for the word `PlaneMad` whereas `users:PlaneMad` will return results for the user PlaneMad. As such, I would expect that results are inconsistent. Closing.

**Comment by planemad** [comment]
Searching `user:planemad` gives results from other users which does not seem to be connected to me in any way. Can you check?

`users:planemad` gives no results. So its `user` and not `users` right?

**Comment by batpad** [comment]
@planemad it is `users` and usernames on OSM are case sensitive so you would search for `users:PlaneMad`. Please close if this works.

**Comment by planemad** [comment]
works :+1:
