### ISSUE TITLE
Structure listings

### ISSUE THREAD

**Issue by lxbarth** [mapbox/osm-comments-frontend#30]
@batpad @geohacker - again, great work here. I think we can structure the content in listing better with some small changes.

Goals:
- See quickly what's been said last (a little like your messages app on ios or Android)
- Show clearly number of comments, time of first note / changeset, time of last post
- Simplify where possible

Wires (intent here is to show functionality, actual layout can differ):
## Comments page

![image](https://cloud.githubusercontent.com/assets/98233/12091845/76d40954-b2ae-11e5-84a6-f5f49430f6f0.png)
## Notes page

corresponding changes on notes page:

![image](https://cloud.githubusercontent.com/assets/98233/12091830/611f79ea-b2ae-11e5-8d81-0d1c8d66d2e6.png)

cc @mikelmaron

**Comment by lxbarth** [comment]
Related from @planemad here #18 

> Default sorting is based on date of last comment but is not very obvious on the UI.
> 
> Something like `Last comment: 12 days ago` would help

**Comment by batpad** [comment]
@lxbarth looks good to me. This needed some changes on the API to return data about the last comment, which I've fixed. Proceeding to make the front-end changes.

**Comment by batpad** [comment]
This is deployed here - http://mapbox.github.io/osm-comments layout slightly differs from suggestion, but all the features are implemented. Please re-open if something does not look right.
