### ISSUE TITLE
Name?

### ISSUE THREAD

**Issue by lxbarth** [mapbox/osm-comments-frontend#31]
@batpad @mikelmaron @geohacker - 

Should we just call this osmcomments?

https://www.mapbox.com/osmcomments

**Comment by mikelmaron** [comment]
I liked the suggestion of osm-conversations, if we were going to change the
name.

Sensitive to @batpad's hassle of changing all three repos and deployment
configuration just for the name

**Comment by batpad** [comment]
So, this conundrum is a bit due to the fact that we are using `gh-pages` / `mb-pages` to host, which means our URL and repository name are coupled. For now, let's just go with `osmcomments` and can re-visit when we have `labs.mapbox.com`? Does that sound okay?

**Comment by mikelmaron** [comment]
:ok: by me

**Comment by lxbarth** [comment]
Ok. Minor chnge: lets do osm-comments with dashes. In line with
osm-edit-report

**Comment by batpad** [comment]
Renamed frontend repository to osm-comments. Closing.
