### ISSUE TITLE
About

### ISSUE THREAD

**Issue by lxbarth** [mapbox/osm-comments-frontend#32]
@batpad there should be a minimal about page (about modal) describing what this app is. Think of someone landing on the app without any context.
- brief description
- link to mapping wiki

**Comment by batpad** [comment]
So, I got the about modal working in React. I'm going to need a little help with the text. Below is very rough and really just place-holder while I worked on the implementation.

<img width="725" alt="screenshot 2016-01-15 10 56 53" src="https://cloud.githubusercontent.com/assets/72280/12346065/c58e9de0-bb76-11e5-9abb-f225be97bd45.png">

@lxbarth @mikelmaron @geohacker, could you post recommendations. I'll work on this as well and update here once I improve it.

**Comment by mikelmaron** [comment]
How's this? Where XXXX is a link to docs or the blog post...

> OSM Comments was developed to help Mapbox Data Team track conversations in OpenStreetMap. And it's built for anyone to search notes and changeset discussions involving any OpenStreetMap user.
> 
> Add "users:<user_names>" in the search bar to find other discussions. For example, "users:geohacker,Planemad" will find notes and changeset discussions only for these users.
> 
> Read more on XXXX.

**Comment by batpad** [comment]
Implemented. Closing.
