### ISSUE TITLE
Editing purely relations won't have bbox

### ISSUE THREAD

**Issue by maning** [mapbox/osm-comments-frontend#34]
No bbox == No map 
See: https://www.openstreetmap.org/api/0.6/changeset/36082110/download

![screen shot 2016-01-07 at 15 15 46](https://cloud.githubusercontent.com/assets/353700/12167334/8e943654-b551-11e5-9427-c8df4d19ca28.png)

**Comment by batpad** [comment]
Right, so this is in cases where the only changes made in the changeset were relations so the bbox is `null`. I guess we just need to make sure the height remains consistent. @maning leave the area taken up by the map blank? Or display whole world? Or .. ?

**Comment by batpad** [comment]
Have put in a styling fix to make the height not look awkward. Not sure much else can be done here. Closing.
