### ISSUE TITLE
Pills have wrong widths 

### ISSUE THREAD

**Issue by geohacker** [mapbox/osm-comments-frontend#36]
@tristen can you help? :)

![screen shot 2016-01-07 at 16 51 59](https://cloud.githubusercontent.com/assets/371666/12169520/010c6ab4-b55f-11e5-8686-598b01595a9a.png)

**Comment by tristen** [comment]
The wrapping container has a fixed width therefore the child elements (the links) should have widths that equal half the parent width.

``` html
<div class='col3 rounded-toggle clearfix'>
  <a href='#' class='col6 center'>Show unreplied</a>
  <a href='#' class='col6 center'>Show all</a>
</div>
```

**Comment by tristen** [comment]
As an aside, I wouldn't use `<a>` elements for this. These aren't links and you have to reset their behaviour because of it (i.e. `stopPropagation`). These look like radio inputs so make them radio inputs.
