### ISSUE TITLE
The blurb is hugging the box border

### ISSUE THREAD

**Issue by geohacker** [mapbox/osm-comments-frontend#38]
![screen shot 2016-01-07 at 16 54 22](https://cloud.githubusercontent.com/assets/371666/12169561/589da806-b55f-11e5-882d-e11b307a4c4d.png)

@tristen can you help?

**Comment by tristen** [comment]
There's a `space-right1` class you can use in base that add's `margin-right: 10px;`. Each box's markup would look roughly like this:

``` html
<div class='col12 clearfix pad2 keyline-all'>
  <div class='col8'>
    <div class='space-right1'>
      Text content goes here.
    <div>
  <div>
  <div class='col4'>
    Image goes here
  </div>
</div>
```

Or, you could apply half the padding to each column container that's currently being used for the parent wrapper.

``` html
<div class='col12 clearfix pad1x pad2y keyline-all'>
  <div class='col8 pad1x'>
    Text content goes here.
  <div>
  <div class='col4 pad1x'>
    Image goes here
  </div>
</div>
```

**Comment by tristen** [comment]
Whoops! I haven't had my coffee and mis-read this issue. I think the markup options above should help in this case. Looks like a fixed height might be being applied to the parent container? I would avoid this.

_Edit_ Seeing this [online now](https://mapbox.com/osm-comments). Yeah, drop the `rowN` rules. These will cause more problems than good in this case. Design these containers to accommodate a flexible structure.
