### ISSUE TITLE
Design adjustments

### ISSUE THREAD

**Issue by tatsvc** [mapbox/osm-comments-frontend#44]
Hi @batpad, congrats on launching the osm-comments page!

I have a few design feedback suggestions to make the page look a little bit more polished:
### Header part

![instructions](https://cloud.githubusercontent.com/assets/2894119/12430867/1f9f5058-bec0-11e5-9fdd-f43fe08b64d2.jpg)
#### 1. The Mapbox logo

By adding the `dark` class to this container element of the logo, it will be white instead of cyan, which will look a bit cleaner on that background.
#### 2. The navigation/tool bar

Instead of using `row1` to set the height of this element, you can use `pad1y` which will give all the elements a little bit more vertical space. 
#### 3. Search field

It would be nice if the search field is right aligned with the rest of the content on the page. You can use `pin-right` on the parent element, and you'll have to add a `contain` class to the limiter which holds all of the elements in this bar. Using the `contain` class will set `position: relative` so you can absolute position the search field with `pin-right`.

Like this:

![image](https://cloud.githubusercontent.com/assets/2894119/12430790/ac0b78f6-bebf-11e5-8b8e-93ebb611f43f.png)
### Comment boxes

In general my main feedback would be to give all the different elements in these boxes a little bit more breathing space. There's a lot going on right now, which makes it hard to quickly scan the content.

One thing that always helps is adding `prose` to text elements, the [prose class](https://www.mapbox.com/base/styling/text-blocks/) will automatically make the line-height bigger and add margin-bottoms where needed. I would also recommend to not use the `row` class too much, but just let the elements itself decide how much vertical space the should take up, and add padding or margin if needed.

Please ping me if you have any questions, or if you want to talk through any of these suggestions!

**Right now**:
![image](https://cloud.githubusercontent.com/assets/2894119/12431150/d2497c0a-bec1-11e5-9020-d9e6fa8490e4.png)

**Suggestions**:
![image](https://cloud.githubusercontent.com/assets/2894119/12431155/d6844b1a-bec1-11e5-9e59-a99f306221bb.png)

In this snippet you can see some of the classes I added/removed (mostly `prose` `pad0y` `small` `quiet`)

```
<div class="clearfix box round pad2 blurb" data-reactid=".0.1.0.$500264"><div class="" data-reactid=".0.1.0.$500264.0"><div class="col8 row2" data-reactid=".0.1.0.$500264.0.0"><div class="clearfix" data-reactid=".0.1.0.$500264.0.0.0"><div class="col12" data-reactid=".0.1.0.$500264.0.0.0.0"><h3 class="fancy inline-heading middle inline fl" data-reactid=".0.1.0.$500264.0.0.0.0.0"><a href="https://www.openstreetmap.org/note/500264" target="_blank" data-reactid=".0.1.0.$500264.0.0.0.0.0.0">500264</a></h3><span class="button short fill-green button-status button-inline pad1x fl space-top0 space-left1" data-reactid=".0.1.0.$500264.0.0.0.0.1">Open</span></div></div><div class="quiet pad0y small" data-reactid=".0.1.0.$500264.0.0.1"><a class="icon account" title="User" href="https://www.openstreetmap.org/user/andygol" target="_blank" data-reactid=".0.1.0.$500264.0.0.1.0">andygol</a><span data-reactid=".0.1.0.$500264.0.0.1.1"> |</span><span class="icon time" href="#" title="Date" data-reactid=".0.1.0.$500264.0.0.1.2">a day ago</span><span data-reactid=".0.1.0.$500264.0.0.1.3"> |</span><span class="icon contact" title="Number of comments" data-reactid=".0.1.0.$500264.0.0.1.4">9</span><span data-reactid=".0.1.0.$500264.0.0.1.5"> |</span><a class="icon crosshair" href="#" data-reactid=".0.1.0.$500264.0.0.1.6">JOSM</a></div><div class="prose pad1y quiet" data-reactid=".0.1.0.$500264.0.0.2"><span data-reactid=".0.1.0.$500264.0.0.2.0">Can anyone investigate on the ground an  amount of mini-roundabouts here? For now there are mapped 6 instead of 5, as I can see at https://youtu.be/DmvHZ4omB2A. And tracing is not accurate :(</span><div class="space-top1" data-reactid=".0.1.0.$500264.0.0.2.1"><span class="icon contact comment-user quiet" title="Comment" data-reactid=".0.1.0.$500264.0.0.2.1.0"><a class="" href="https://www.openstreetmap.org/user/SK53" target="_blank" data-reactid=".0.1.0.$500264.0.0.2.1.0.0">SK53</a><span data-reactid=".0.1.0.$500264.0.0.2.1.0.1"> </span></span><span class="quiet" data-reactid=".0.1.0.$500264.0.0.2.1.1">commented a day ago</span><div class="comment-last pad1rt" data-reactid=".0.1.0.$500264.0.0.2.1.2">@andygol I'd tend to agree with your interpretation that the '6th' roundabout is an artefact of the imagery. I think the whole principle of 'magic' roundabouts requires as many mini-roundabouts as exit roads. There is Mapillary sequence, but from a cyclist so not completely useful: http://www.mapillary.com/map/im/xIBy8JnGDU8IxPd7MhxSGA/photo.

I think your first comment stands: it needs someone to check it out on the ground.</div></div></div></div><div class="col4 clip" data-reactid=".0.1.0.$500264.0.1"><img src="https://api.mapbox.com/v4/mapbox.streets/-1.7712155,51.5628654,13/500x300.png?access_token=pk.eyJ1Ijoic2FuamF5YiIsImEiOiI3NjVvMFY0In0.byn_eCZGAwR1yaPeC-SVKw" data-reactid=".0.1.0.$500264.0.1.0"></div></div></div>
```
### Responsive

Also make sure to always check what the page will look like on smaller screen, sometimes some elements can behave in a weird way:
![image](https://cloud.githubusercontent.com/assets/2894119/12431278/9e5dc990-bec2-11e5-8244-579fb0a870ee.png)

**Comment by lxbarth** [comment]
@tatsvc - awesome feedback. Thank you.

@batpad - i'm thinking two things:
1. Can you apply, update osm-comments and also update screenshots in blog posts? This will look a lot tighter.
2. We should make a design review part of the roll out process. Just chatted w/ @tatsvc, she'd be happy to do that.

cc @geohacker @mikelmaron @tristen @samanpwbb @mayagao

**Comment by mikelmaron** [comment]
fantastic plan for future roll outs, thank you @tatsvc

**Comment by geohacker** [comment]
@tatsvc thank you! Some of these are my design oversight. 

> We should make a design review part of the roll out process

Yes, please! We opened [tickets](https://github.com/mapbox/osm-comments/issues/38) [to](https://github.com/mapbox/osm-comments/issues/36) [get](https://github.com/mapbox/osm-comments/issues/27) feedback but it obviously didn't cover all of them.

**Comment by batpad** [comment]
Thank you SO MUCH for the detailed design review @tatsvc and apologies for not asking earlier :)

I've made changes and deployed as per your suggestions and things look a lot better: https://mapbox.com/osm-comments

Couple of things I'd appreciate your suggestions on:
- The About modal implementation: The `About` link to trigger it just below the logo looks slightly awkward to me. Any suggestions for improvement? Also, am not super happy with the way the modal looks. Any suggestions?
- From quickly checking on different screen sizes, things look mostly okay to me now - I think with removing the fixed height on the navbar and absolutely positioning search to the right, the `pill` toggle seems to naturally go to the next line when the width is constrained. It does seem, though, on smaller devices that the Changesets / Notes links to the left of the search bar start overlapping with the search bar. Um, any suggestions?

Do let us know if there's anything else that can be improved - can't thank you enough for these :)

**Comment by tatsvc** [comment]
> The About modal implementation: The About link to trigger it just below the logo looks slightly awkward to me. Any suggestions for improvement? Also, am not super happy with the way the modal looks. Any suggestions?

I'm not sure how important this part is, but I would consider moving it to the footer. Maybe we can have a little subtle footer like we have on some of our mapbox.com pages, and add the about link:

![image](https://cloud.githubusercontent.com/assets/2894119/12452537/fb1f8868-bf5c-11e5-835d-d4b871427570.png)

A view suggestions for the modal:
- Make it a little bit wider, so the sentences are easier to read
- Add a little bit more padding
- Add the `prose` class to the paragraphs, so the line height is a big taller
- Maybe turn the github link into a button with a cute little icon (and to add some color) `space-top2 button icon github pad4x`

![image](https://cloud.githubusercontent.com/assets/2894119/12452691/c5103c3a-bf5d-11e5-8b4a-9f116a479ad0.png)

> It does seem, though, on smaller devices that the Changesets / Notes links to the left of the search bar start overlapping with the search bar. Um, any suggestions?

Unfortunately base.css doesn't cover all these issues. I would recommend writing some custom css with breakpoints. For the toggle for example:

```
@media only screen and (max-width:1060px) {
  #filters {  min-width: 230px;}
}
```

And then where the search field starts overlapping (you might have to give this absolute positioned element a new class), you'll want to make the position relative again, so it flows to the next line:

```
@media only screen and (max-width:710px) {
      .myPositionedElement {
         position: relative;
         clear: both;
         padding-top: 20px;
   }
    #users {
    width: 100%;
   }
}
```

![image](https://cloud.githubusercontent.com/assets/2894119/12453004/3b69503c-bf5f-11e5-93cd-c629e0ae666c.png)

**Comment by tatsvc** [comment]
And thanks for the changes! Looking awesome! :100:

**Comment by batpad** [comment]
@tatsvc have deployed a new iteration.

The media queries worked like a charm and I think overlapping elements in the search bar on smaller screens is fixed.

I made the Github link a button and added line-spacing to the text in the modal and made the modal a bit wider. Just need to figure out how to make the modal less wide on smaller devices, a little confused on how to do this with the React Modal plugin being used since the styes get added inline by the JS, but I will work on this.

For the `About` link, I don't want to add it to a footer all the way at the bottom for 2 reasons:
- The list can get quite long and I think this gets a bit too buried.
- I hope to add a scrolling pagination soon, in which case, the footer would get pushed further down as more elements load.

Do you think a `position: fixed` really small footer at the bottom right of the screen or so could work?

Thanks!

**Comment by tatsvc** [comment]
> Do you think a position: fixed really small footer at the bottom right of the screen or so could work?

Sure!

**Comment by batpad** [comment]
I think we're done here :)
Closing.
